### ISSUE TITLE
Android Not Functional

### ISSUE THREAD

**Issue by jatsrt** [tinycreative/react-native-intercom#49]
Latest build/release 4.2.0

Looking at the code, this seems to be iOS only, but Android will not load because of it.

`undefined is not an object (evaluating 'IntercomEventEmitter.UNREAD_CHANGE_NOTIFICATION')
IntercomClient
    IntercomClient.js:26
<unknown>
    IntercomClient.js:241
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:65
_require
    require.js:49
<unknown>
    authStore.js:19
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:65
_require
    require.js:49
<unknown>
    index.js:5
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:65
_require
    require.js:49
<unknown>
    index.js:21
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:65
_require
    require.js:49
<unknown>
    index.android.js:1
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:58
_require
    require.js:49
global code
    require-0.js:1
`

**Comment by browniefed** [comment]
Ah shoot sorry about this will get a fix out later today

**Comment by browniefed** [comment]
Let me know if this got fixed in v4.3.
(I don't actually use this so might need to just add a `Platform` check or just go add the Java bits)

**Comment by jatsrt** [comment]
Still an issue, in the constructor, line 27-31.

If I get some time, I might go and try to add the java bits and do a pull request.  I will be using this on both platforms pretty fully.

**Comment by jatsrt** [comment]
Added the pull request, sorry fixed two things in one request, not the best contributor.

**Comment by browniefed** [comment]
"I fixed more things, I'm not the best contributor"... uh no that's fantastic. Thank you so much for this, try to manage all of this when I don't actually use it. So all the help I can get is great.

**Comment by browniefed** [comment]
Published in v4.4 now

**Comment by jatsrt** [comment]
I'll be using this quite a bit, so I will contribute as I can.

**Comment by maxx-coffee** [comment]
Hey guys,

It looks like im still having this issue on 4.6.0.  I have tried clearing cache and re-installing.  Installing directly from the master branch on github vs regular npm install.  

Im not entirely sure how to debug this issue as I have VERY little android experience.  Do either of you have any ideas why I would keep seeing this?

**Comment by jatsrt** [comment]
Could you post the problem you are seeing?  Is it the exact same error?  I've been using this pretty reliably since Nov 7

**Comment by nicholeuf** [comment]
We are having this same issue when we upgraded to RN 0.28 using v4.6 of react-native-intercom.

**Comment by maxx-coffee** [comment]
I just got back to seeing this. I had to do some research on how to properly install Intercom for Android.  

After I imported `import com.robinpowered.react.Intercom.IntercomPackage;`  and added `new IntercomPackage()`  to my package array everything seems to work.
